### ISSUE TITLE
Filtering for the list of sessions by date

### ISSUE THREAD

**Issue by sabbaka** [Scribery/cockpit#1]
Based on user stories description.
Add two date time pickers to the upper part of user sessions list.
Default range will month back from current date.
Format of date time should match back-end format.

**Comment by sabbaka** [comment]
It was done. It can be closed or we might add time also ( or it could be done in next milestone ).

**Comment by spbnick** [comment]
Let's open a new issue based on design discussions. This one is done, thank you!
