### ISSUE TITLE
Switch to using TLOG_REC journal field for identifying recordings

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#11]
Instead of keeping, passing around, and filtering messages with boot ID, audit session ID and PID, use TLOG_REC logged by latest tlog master.

**Comment by sabbaka** [comment]
I've made the switch. I've added for now to pull request ( for now ).
Maybe I will add some changes.

**Comment by sabbaka** [comment]
I'll close issue now, because pull request was accepted.
