### ISSUE TITLE
URL response for filters and particular recorded session id

### ISSUE THREAD

**Issue by sabbaka** [Scribery/cockpit#13]
This will require remake of current handling of URL. Possible to make with GET parameters or additional attributes.

**Comment by spbnick** [comment]
Take a look at http://cockpit-project.org/guide/latest/cockpit-location.html
Note that "options" are URL parameters in Cockpit parlance.

**Comment by spbnick** [comment]
Apparently "Fix" doesn't work with github. It should've been "Fixes", I assume. Closing.
