### ISSUE TITLE
Resizeble terminal 

### ISSUE THREAD

**Issue by sabbaka** [Scribery/cockpit#18]
Right now terminal looks ugly, possible CSS issue. This should be improved step by step.
Here are steps to be done:
- Fix width and height of a terminal. 
- Let user to change it's size. 
- Resize terminal by tlog-play.

**Comment by sabbaka** [comment]
I think it's possible to use CSS3 property resize. I think we will definitely need to create our own class for React terminal component. It's related to different resize events, resize of parent div will be watched instead of window resize and also buttons for playback manage.

**Comment by sabbaka** [comment]
Well, I'm stuck with this one task for sometime, but will figure out soon. I'm not sure where the problem is now, but terminal is always trying to fill all the space given by parent div, though it reads cols and rows properly. My idea is to use CSS3 property resize ( or something similar for jQuery, because of possible issues with browsers compatibility ) and to fire event of resize and base on values of width and height calculate rows and cols for terminal.

**Comment by spbnick** [comment]
Check with the fellow web developer from FreeIPA team, perhaps he has some ideas.

**Comment by sabbaka** [comment]
I've just found a way how I will make it. After struggling with jquery-resizable ( from ui set ) I've found very nice lib already in Cockpit which is called jquery-flot and it has same functional jquery-flot-resize and it fires event on resize which is done by resize CSS property.

**Comment by sabbaka** [comment]
I've made it resizable, right now it's very ugly, but resize is working. We'll need to think how it will work with pre-recorded sessions and their size. I won't push this now.
Here how it looks like:
https://youtu.be/eXojaXqRKso

**Comment by sabbaka** [comment]
I'll close issue now, because pull request was accepted.
