### ISSUE TITLE
Implement basic playback controls

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#23]
Let's start with play/pause, fast-forward, slow-play, rewind to start.

**Comment by spbnick** [comment]
I got some playback controls working in my private branch of tlog: play/pause, double/halve/reset speed, working on fast-forward to end. Hope to finish soon, then we'll be able to do some controls in the UI.

**Comment by spbnick** [comment]
I uploaded the mostly done implementation here: https://github.com/Scribery/tlog/pull/117
I'll do some minor tweaks before merging, but it's possible already to implement most of the planned playback controls with the pull request. I'll add skip-to-next "frame" later.

**Comment by sabbaka** [comment]
Great, I'll start working on this. What are the controls?

**Comment by spbnick** [comment]
Take a look at man tlog-play after installing. We'll also need to use
"--persist" option that I just added.

**Comment by sabbaka** [comment]
Well, keys are already working in browser without any changes to JS code.
I can add buttons also, I'll describe this in design.

**Comment by spbnick** [comment]
Yes, the point of this is to add buttons, thank you.

**Comment by spbnick** [comment]
I also added the skip-to-next "frame" key (".") support, and merged.
