### ISSUE TITLE
Provide minute precision for recording filtering time ranges

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#27]
From [user stories](https://github.com/Scribery/meta/blob/master/playback_ui_user_stories.md):

* I should be able to choose the sessions that were recorded during a
  specific period of time. 
* I should be able to enter the range to narrow the search.
* I should be able to alter the range to widen or to further narrow down the
  search
* The range should have reasonable defaults (for example last 30 days) when
  the selection screen is presented
* The range should allow up to minute granularity with hour-aligned
  defaults
* The controls should be user friendly, so that I do not have to type date
  or time as text into the search criteria, but could select some
  pre-defined ranges
* The range might be expressed as a range of dates as well as a range from
  now till X days back

**Comment by sabbaka** [comment]
About user-friendly, I'll add another type of date picket with time also - right now there is no such in Cockpit at all - time needs to be entered manually.

**Comment by sabbaka** [comment]
How much is it important to support different time formats, like 24 hours or AM/PM? Should it be there?

**Comment by spbnick** [comment]
Check what Cockpit supports in general, how they handle locales and browser language. If they do support different time formats, so should we. Otherwise, not at this moment.

**Comment by sabbaka** [comment]
I was working today on adding time to picker also and end up stuck with some react-lite error - basically, I'm doing the same with two different datepickers bootstrap-datepicker ( which I've add, but it also was already inside node_nodules-patternfly/node_modules - which is sort of strange - why would it be like this and not as a dependency - probably npm specifics ) and eonasdan-bootstrap-datetimepicker ( which I also have installed from npm and then also found in patternfly ) - so they both are sending same string ( I was testing only with date string ) but if I'm using eonasdan-bootstrap-datetimepicker I'm getting this error, which is really strange.
![screenshot from 2017-09-01 16-43-47](https://user-images.githubusercontent.com/5558501/29974911-c3894b6a-8f34-11e7-90ef-6fb00224ea45.png)
Quite disappointing.

**Comment by spbnick** [comment]
I see. I would suggest asking on #cockpit.

**Comment by sabbaka** [comment]
Fixed by https://github.com/Scribery/cockpit/pull/32
