### ISSUE TITLE
Consider implementing playback location bar with on-host playback

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#4]
It would be nice to have a playback location bar in Cockpit, even with the on-host playback already. We might be able to do this if we manage to get playback position from tlog-play (#5).

**Comment by sabbaka** [comment]
I decided to start with adding progress bar which value should be determined by difference from start and end of the session ( we have those ) values. I've difference in ms and added tick for each ms and next try was with second - right now end of playback for session is ended earlier then counter. I'm not sure what is the problem making this, but I'll find out.
Demo: https://youtu.be/inrNaIWRqSU
It might be JavaScript or term.js or tlog-play issue.

**Comment by spbnick** [comment]
This will be unreliable and confusing unless we get progress information from tlog-play directly, and that needs implementing in tlog-play (Scribery/tlog#107).

**Comment by spbnick** [comment]
It is difficult to inject escape sequences into an already existing terminal I/O stream, so we better focus on making this work with a fully-JavaScript-based player.
