### ISSUE TITLE
Rebase on latest Cockpit master

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#45]

**Comment by spbnick** [comment]
Rebased on a7e37c0c527. Keeping the issue open for following rebase.

**Comment by sabbaka** [comment]
Is there some mistake? Because, I've just made a checkout for this commit, but there is no pkg/session_recording.

**Comment by spbnick** [comment]
Don't checkout that commit. Update "scribery" branch. I rebased it on *that commit*.

**Comment by spbnick** [comment]
You'll need to fetch from the remote and then rebase on the remote branch, since it was rewritten (force-updated).

**Comment by sabbaka** [comment]
https://github.com/Scribery/cockpit/pull/82
