### ISSUE TITLE
Do not run two journalctl's on playback

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#58]
At the moment, when recording is being played back, Cockpit runs two journalctl processes: one for updating recording information, another for loading the recording itself. Make sure there is only one journalctl running in that case.

**Comment by sabbaka** [comment]
I've checked this issue and found another bug, at some moment there were three journalctls, related to dates changes and not getting tlog's UID, so I moved this part to `componentWillMount`

**Comment by sabbaka** [comment]
I have created one possible solution for this. PR #69

**Comment by spbnick** [comment]
I think this is not actually an issue and was reported mistakenly. I think I was confused when reporting this. There should be two journalctl instances: one for loading information on all and/or particular entries (without the `MESSAGE` field), and another for playing a particular entry. I suspect the third journalctl appears at the moment the `Player` restarts the initial instance to continue following ongoing recordings.

**Comment by sabbaka** [comment]
Yes, it makes sense, I'm closing this issue.
