### ISSUE TITLE
Consider implementing log correlation window with on-host playback

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#6]
If communicating current terminal playback position is proven possible with on-host playback (#5), consider adding a window displaying other log messages recorded at the current position (say within 5 seconds), in the same audit session, updated as playback position changes.

**Comment by sabbaka** [comment]
It might require launch of journalctl and different filtering on client side to get rid of logs from tlog itself again.

**Comment by spbnick** [comment]
We can start with just filtering audit log messages. Problem is journalctl doesn't support inverse matching, but we can match on audit session ID fields.

**Comment by sabbaka** [comment]
Exactly. Good, I'll start with audit logs for now. Thanks.
I'm thinking on time period for grabbing logs, it could be slightly bigger than session length ( depending on length of session - seconds, minutes, hours ) and maybe there should be field to specify this.

**Comment by spbnick** [comment]
It is difficult to inject escape sequences into an already existing terminal I/O stream, so we better focus on making this work with a fully-JavaScript-based player.

**Comment by spbnick** [comment]
It is difficult to inject escape sequences into an already existing terminal I/O stream, so we better focus on making this work with a fully-JavaScript-based player.
